test: Fix failing exception check in new thread busy test
New thread busy test from 1238170f68e8fa7ae41c79465df5cdae34d568e9
(https://github.com/bitcoin-core/libmultiprocess/pull/214) is checking for
"Future already retrieved" error with string match which is fragile and does
not work on all platforms, resulting in error:

test/mp/test/test.cpp:339: error: failed: expected e.what() == std::string("Future already retrieved") [std::future_error: Future already retrieved == Future already retrieved]

This change fixes the test to check for an error code instead.

Separately there seems to be a problem with this KJ_EXPECT call because it
prints error output without causing the test to fail. This may be happening
because it is not called on the main test thread. That issue is not addressed
by this change and requires more followup.