clang-tidy: Fix bugprone-move-forwarding-reference error
/ci_container_base/include/mp/type-interface.h:47:75: error: forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead [bugprone-move-forwarding-reference,-warnings-as-errors]
https://cirrus-ci.com/task/6187773452877824?logs=ci#L4712

Error was caused by mp/type-interface.h CustomBuildField field using std::move
instead of std::forward.

Just switching from std::move to std::forward, however, would lead to another
error in the CustomMakeProxyServer function which is expecting an rvalue, not
an lvalue.

That error could be fixed by changing CustomMakeProxyServer to accept lvalues
and copy the shared_ptr, which would have a slight performance cost. But it is
better to resolve the problem at the root and switch to perfect forwarding
everywhere, all the way up the call stack. This required some small changes to
the code generator and clientInvoke.